# cloudbuild.yaml

steps:
  # 1) Docker-Image bauen und taggen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT}/cloud-run-source-deploy/${_SERVICE}/${_SERVICE}:${SHORT_SHA}'
      - '.'

  # 2) Mit gcloud in Cloud Run deployen
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image=${_REGION}-docker.pkg.dev/${_PROJECT}/cloud-run-source-deploy/${_SERVICE}/${_SERVICE}:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --concurrency=80 \
          --port=8080 \
          --set-env-vars=server_id=${_SERVER_ID},bot_key=${_BOT_KEY}

# 3) Damit das erzeugte Image in der History auftaucht
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT}/cloud-run-source-deploy/${_SERVICE}/${_SERVICE}:${SHORT_SHA}'

# Nur Konstanten hier, alles andere kommt aus Deinem Trigger
substitutions:
  _PROJECT: 'lotus-gaming-bot'      # Dein GCP-Projekt
  _REGION: 'europe-west1'           # Region Deiner Registry/Cloud Run
  _SERVICE: 'lotusgamingde'         # Name Deines Cloud-Run-Services

# Verlängere Timeout auf 10 Minuten (optional)
timeout: '600s'
