name: Update-Runtime-Logs
on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli@3.14.0

      - name: Pull latest 100 runtime logs
        env:
          RAILWAY_TOKEN:   ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT: ${{ vars.RAILWAY_PROJECT }}
          RAILWAY_SERVICE: ${{ vars.RAILWAY_SERVICE }}
        run: |
          mkdir -p logs/railway
      
          # 1) Projekt in dieses Verzeichnis linken (idempotent)
          railway link -p "$RAILWAY_PROJECT" --yes || true
      
          # 2) Logs holen (ohne --project, ohne --limit)
          railway logs --service "$RAILWAY_SERVICE" --json \
            | head -n 100 > logs/railway/latest_logs.json
      
          echo "Wrote $(wc -l < logs/railway/latest_logs.json) lines"

      - name: Commit & push new log file
        run: |
          git config user.name  "CI Bot"
          git config user.email "ci@example.com"
          git add logs/railway/latest_logs.json
          git commit -m "chore(logs): update latest runtime logs" || echo "No changes"
          git push

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: railway-latest-log
          path: logs/railway/latest_logs.json
