name: Update-Runtime-Logs
on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli@3.14.0

      - name: Pull latest 100 runtime logs
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          mkdir -p logs/railway
          railway --project ${{ vars.RAILWAY_PROJECT }} logs \
            --service ${{ vars.RAILWAY_SERVICE }} \
            --json --limit 100 > logs/railway/latest_logs.json
          echo "Wrote $(wc -l < logs/railway/latest_logs.json) lines to logs/railway/latest_logs.json"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: railway-latest-log
          path: logs/railway/latest_logs.json
